/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as PedidoConfirmadoRouteImport } from './routes/pedido-confirmado'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMiCuentaRouteImport } from './routes/_authenticated/mi-cuenta'
import { Route as AuthenticatedMisPedidosRouteImport } from './routes/_authenticated/mis-pedidos'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'
import { Route as AuthenticatedMisPedidosIdRouteImport } from './routes/_authenticated/mis-pedidos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoConfirmadoRoute = PedidoConfirmadoRouteImport.update({
  id: '/pedido-confirmado',
  path: '/pedido-confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMiCuentaRoute = AuthenticatedMiCuentaRouteImport.update({
  id: '/mi-cuenta',
  path: '/mi-cuenta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMisPedidosRoute = AuthenticatedMisPedidosRouteImport.update({
  id: '/mis-pedidos',
  path: '/mis-pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMisPedidosIdRoute =
  AuthenticatedMisPedidosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedMisPedidosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/mis-pedidos': typeof AuthenticatedMisPedidosRouteWithChildren
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/mis-pedidos/$id': typeof AuthenticatedMisPedidosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/mis-pedidos': typeof AuthenticatedMisPedidosRouteWithChildren
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/mis-pedidos/$id': typeof AuthenticatedMisPedidosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/_authenticated/mis-pedidos': typeof AuthenticatedMisPedidosRouteWithChildren
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/_authenticated/mis-pedidos/$id': typeof AuthenticatedMisPedidosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carrito'
    | '/catalogo'
    | '/checkout'
    | '/pedido-confirmado'
    | '/admin'
    | '/mi-cuenta'
    | '/mis-pedidos'
    | '/categoria/$slug'
    | '/producto/$slug'
    | '/mis-pedidos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carrito'
    | '/catalogo'
    | '/checkout'
    | '/pedido-confirmado'
    | '/admin'
    | '/mi-cuenta'
    | '/mis-pedidos'
    | '/categoria/$slug'
    | '/producto/$slug'
    | '/mis-pedidos/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/carrito'
    | '/catalogo'
    | '/checkout'
    | '/pedido-confirmado'
    | '/_authenticated/admin'
    | '/_authenticated/mi-cuenta'
    | '/_authenticated/mis-pedidos'
    | '/categoria/$slug'
    | '/producto/$slug'
    | '/_authenticated/mis-pedidos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CarritoRoute: typeof CarritoRoute
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRoute
  PedidoConfirmadoRoute: typeof PedidoConfirmadoRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido-confirmado': {
      id: '/pedido-confirmado'
      path: '/pedido-confirmado'
      fullPath: '/pedido-confirmado'
      preLoaderRoute: typeof PedidoConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-cuenta': {
      id: '/_authenticated/mi-cuenta'
      path: '/mi-cuenta'
      fullPath: '/mi-cuenta'
      preLoaderRoute: typeof AuthenticatedMiCuentaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mis-pedidos': {
      id: '/_authenticated/mis-pedidos'
      path: '/mis-pedidos'
      fullPath: '/mis-pedidos'
      preLoaderRoute: typeof AuthenticatedMisPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mis-pedidos/$id': {
      id: '/_authenticated/mis-pedidos/$id'
      path: '/$id'
      fullPath: '/mis-pedidos/$id'
      preLoaderRoute: typeof AuthenticatedMisPedidosIdRouteImport
      parentRoute: typeof AuthenticatedMisPedidosRoute
    }
  }
}

interface AuthenticatedMisPedidosRouteChildren {
  AuthenticatedMisPedidosIdRoute: typeof AuthenticatedMisPedidosIdRoute
}

const AuthenticatedMisPedidosRouteChildren: AuthenticatedMisPedidosRouteChildren =
  {
    AuthenticatedMisPedidosIdRoute: AuthenticatedMisPedidosIdRoute,
  }

const AuthenticatedMisPedidosRouteWithChildren =
  AuthenticatedMisPedidosRoute._addFileChildren(
    AuthenticatedMisPedidosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMiCuentaRoute: typeof AuthenticatedMiCuentaRoute
  AuthenticatedMisPedidosRoute: typeof AuthenticatedMisPedidosRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMiCuentaRoute: AuthenticatedMiCuentaRoute,
  AuthenticatedMisPedidosRoute: AuthenticatedMisPedidosRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CarritoRoute: CarritoRoute,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRoute,
  PedidoConfirmadoRoute: PedidoConfirmadoRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ProductoSlugRoute: ProductoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
